language: node_js

os: linux


node_js:
  - '12'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate:gh-pages

deploy:
  stratege: git
  provider: pages
  cleanup: true
  token: $GITHUB_ACCESS_TOKEN
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: master