language: node_js

os: linux

dist: xenial

node_js:
  - '12'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - yarn install
  - yarn generate:gh-pages

script:
  - echo "Skipping tests"

deploy:
  strategy: git
  provider: pages
  cleanup: false
  skip_cleanup: true
  token: $GITHUB_ACCESS_TOKEN
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: master